import 'dart:math';
import 'package:countries_world_map/countries_world_map.dart';
import 'package:countries_world_map/data/maps/world_map.dart';
import 'package:flutter/material.dart';
import 'country_detail_screen.dart';

class RandomWorldMapGenerator extends StatefulWidget {
  RandomWorldMapGenerator({Key? key}) : super(key: key);

  @override
  _RandomWorldMapGeneratorState createState() =>
      _RandomWorldMapGeneratorState();
}

class _RandomWorldMapGeneratorState extends State<RandomWorldMapGenerator> {
  List<Color> colors = [
  Colors.indigo.shade900,
  Colors.blue.shade400,
  Colors.pink.shade300,
  Colors.red.shade700,
  Colors.teal.shade500,
  Colors.orange.shade600,
  Colors.purple.shade800,
  Colors.green.shade700,
  Colors.yellow.shade600,
  Colors.cyan.shade500,
  Colors.amber.shade700,
  Colors.deepPurple.shade400,
  Colors.lime.shade800,
  Colors.lightBlue.shade300,
  Colors.deepOrange.shade400,
  Colors.pink.shade200,
  Colors.brown.shade400,
  Colors.grey.shade700,
  Colors.blueGrey.shade500,
];


  final _random = Random();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      child: Stack(
        children: [
          InteractiveViewer(
            maxScale: 75.0,
            child: Center(
              child: Row(
                children: [
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.92,
                    // Actual widget from the Countries_world_map package.
                    child: SimpleMap(
                      countryBorder: CountryBorder(color: Colors.white),
                      instructions: SMapWorld.instructionsMercator,
                      callback: (id, name, tapDetails) {
  Navigator.of(context).push(MaterialPageRoute(
    builder: (context) => CountryDetailScreen(
      countryName: id,
      onVisitedChanged: (String countryName, bool visited) {
        // Handle the state change for visited countries
      },
    ),
  ));
                      },
                      colors: SMapWorldColors(
                        aD: colors[_random.nextInt(19)],
                        aE: colors[_random.nextInt(19)],
                        aF: colors[_random.nextInt(19)],
                        aG: colors[_random.nextInt(19)],
                        aI: colors[_random.nextInt(19)],
                        aL: colors[_random.nextInt(19)],
                        aM: colors[_random.nextInt(19)],
                        aN: colors[_random.nextInt(19)],
                        aO: colors[_random.nextInt(19)],
                        aQ: colors[_random.nextInt(19)],
                        aR: colors[_random.nextInt(19)],
                        aS: colors[_random.nextInt(19)],
                        aT: colors[_random.nextInt(19)],
                        aU: colors[_random.nextInt(19)],
                        aW: colors[_random.nextInt(19)],
                        aX: colors[_random.nextInt(19)],
                        aZ: colors[_random.nextInt(19)],
                        bA: colors[_random.nextInt(19)],
                        bB: colors[_random.nextInt(19)],
                        bD: colors[_random.nextInt(19)],
                        bE: colors[_random.nextInt(19)],
                        bF: colors[_random.nextInt(19)],
                        bG: colors[_random.nextInt(19)],
                        bH: colors[_random.nextInt(19)],
                        bI: colors[_random.nextInt(19)],
                        bJ: colors[_random.nextInt(19)],
                        bL: colors[_random.nextInt(19)],
                        bM: colors[_random.nextInt(19)],
                        bN: colors[_random.nextInt(19)],
                        bO: colors[_random.nextInt(19)],
                        bQ: colors[_random.nextInt(19)],
                        bR: colors[_random.nextInt(19)],
                        bS: colors[_random.nextInt(19)],
                        bT: colors[_random.nextInt(19)],
                        bV: colors[_random.nextInt(19)],
                        bW: colors[_random.nextInt(19)],
                        bY: colors[_random.nextInt(19)],
                        bZ: colors[_random.nextInt(19)],
                        cA: colors[_random.nextInt(19)],
                        cC: colors[_random.nextInt(19)],
                        cD: colors[_random.nextInt(19)],
                        cF: colors[_random.nextInt(19)],
                        cG: colors[_random.nextInt(19)],
                        cH: colors[_random.nextInt(19)],
                        cI: colors[_random.nextInt(19)],
                        cK: colors[_random.nextInt(19)],
                        cL: colors[_random.nextInt(19)],
                        cM: colors[_random.nextInt(19)],
                        cN: colors[_random.nextInt(19)],
                        cO: colors[_random.nextInt(19)],
                        cR: colors[_random.nextInt(19)],
                        cU: colors[_random.nextInt(19)],
                        cV: colors[_random.nextInt(19)],
                        cW: colors[_random.nextInt(19)],
                        cX: colors[_random.nextInt(19)],
                        cY: colors[_random.nextInt(19)],
                        cZ: colors[_random.nextInt(19)],
                        dE: colors[_random.nextInt(19)],
                        dJ: colors[_random.nextInt(19)],
                        dK: colors[_random.nextInt(19)],
                        dM: colors[_random.nextInt(19)],
                        dO: colors[_random.nextInt(19)],
                        dZ: colors[_random.nextInt(19)],
                        eC: colors[_random.nextInt(19)],
                        eE: colors[_random.nextInt(19)],
                        eG: colors[_random.nextInt(19)],
                        eH: colors[_random.nextInt(19)],
                        eR: colors[_random.nextInt(19)],
                        eS: colors[_random.nextInt(19)],
                        eT: colors[_random.nextInt(19)],
                        fI: colors[_random.nextInt(19)],
                        fJ: colors[_random.nextInt(19)],
                        fK: colors[_random.nextInt(19)],
                        fM: colors[_random.nextInt(19)],
                        fO: colors[_random.nextInt(19)],
                        fR: colors[_random.nextInt(19)],
                        gA: colors[_random.nextInt(19)],
                        gB: colors[_random.nextInt(19)],
                        gD: colors[_random.nextInt(19)],
                        gE: colors[_random.nextInt(19)],
                        gF: colors[_random.nextInt(19)],
                        gG: colors[_random.nextInt(19)],
                        gH: colors[_random.nextInt(19)],
                        gI: colors[_random.nextInt(19)],
                        gL: colors[_random.nextInt(19)],
                        gM: colors[_random.nextInt(19)],
                        gN: colors[_random.nextInt(19)],
                        gP: colors[_random.nextInt(19)],
                        gQ: colors[_random.nextInt(19)],
                        gR: colors[_random.nextInt(19)],
                        gS: colors[_random.nextInt(19)],
                        gT: colors[_random.nextInt(19)],
                        gU: colors[_random.nextInt(19)],
                        gW: colors[_random.nextInt(19)],
                        gY: colors[_random.nextInt(19)],
                        hK: colors[_random.nextInt(19)],
                        hM: colors[_random.nextInt(19)],
                        hN: colors[_random.nextInt(19)],
                        hR: colors[_random.nextInt(19)],
                        hT: colors[_random.nextInt(19)],
                        hU: colors[_random.nextInt(19)],
                        iD: colors[_random.nextInt(19)],
                        iE: colors[_random.nextInt(19)],
                        iL: colors[_random.nextInt(19)],
                        iM: colors[_random.nextInt(19)],
                        iN: colors[_random.nextInt(19)],
                        iO: colors[_random.nextInt(19)],
                        iQ: colors[_random.nextInt(19)],
                        iR: colors[_random.nextInt(19)],
                        iS: colors[_random.nextInt(19)],
                        iT: colors[_random.nextInt(19)],
                        jE: colors[_random.nextInt(19)],
                        jM: colors[_random.nextInt(19)],
                        jO: colors[_random.nextInt(19)],
                        jP: colors[_random.nextInt(19)],
                        kE: colors[_random.nextInt(19)],
                        kG: colors[_random.nextInt(19)],
                        kH: colors[_random.nextInt(19)],
                        kI: colors[_random.nextInt(19)],
                        kM: colors[_random.nextInt(19)],
                        kN: colors[_random.nextInt(19)],
                        kP: colors[_random.nextInt(19)],
                        kR: colors[_random.nextInt(19)],
                        kW: colors[_random.nextInt(19)],
                        kY: colors[_random.nextInt(19)],
                        kZ: colors[_random.nextInt(19)],
                        lA: colors[_random.nextInt(19)],
                        lB: colors[_random.nextInt(19)],
                        lC: colors[_random.nextInt(19)],
                        lI: colors[_random.nextInt(19)],
                        lK: colors[_random.nextInt(19)],
                        lR: colors[_random.nextInt(19)],
                        lS: colors[_random.nextInt(19)],
                        lT: colors[_random.nextInt(19)],
                        lU: colors[_random.nextInt(19)],
                        lV: colors[_random.nextInt(19)],
                        lY: colors[_random.nextInt(19)],
                        mA: colors[_random.nextInt(19)],
                        mC: colors[_random.nextInt(19)],
                        mD: colors[_random.nextInt(19)],
                        mE: colors[_random.nextInt(19)],
                        mF: colors[_random.nextInt(19)],
                        mG: colors[_random.nextInt(19)],
                        mH: colors[_random.nextInt(19)],
                        mK: colors[_random.nextInt(19)],
                        mL: colors[_random.nextInt(19)],
                        mM: colors[_random.nextInt(19)],
                        mN: colors[_random.nextInt(19)],
                        mO: colors[_random.nextInt(19)],
                        mP: colors[_random.nextInt(19)],
                        mQ: colors[_random.nextInt(19)],
                        mR: colors[_random.nextInt(19)],
                        mS: colors[_random.nextInt(19)],
                        mT: colors[_random.nextInt(19)],
                        mU: colors[_random.nextInt(19)],
                        mV: colors[_random.nextInt(19)],
                        mW: colors[_random.nextInt(19)],
                        mX: colors[_random.nextInt(19)],
                        mY: colors[_random.nextInt(19)],
                        mZ: colors[_random.nextInt(19)],
                        nA: colors[_random.nextInt(19)],
                        nC: colors[_random.nextInt(19)],
                        nE: colors[_random.nextInt(19)],
                        nF: colors[_random.nextInt(19)],
                        nG: colors[_random.nextInt(19)],
                        nI: colors[_random.nextInt(19)],
                        nL: colors[_random.nextInt(19)],
                        nO: colors[_random.nextInt(19)],
                        nP: colors[_random.nextInt(19)],
                        nR: colors[_random.nextInt(19)],
                        nU: colors[_random.nextInt(19)],
                        nZ: colors[_random.nextInt(19)],
                        oM: colors[_random.nextInt(19)],
                        pA: colors[_random.nextInt(19)],
                        pE: colors[_random.nextInt(19)],
                        pF: colors[_random.nextInt(19)],
                        pG: colors[_random.nextInt(19)],
                        pH: colors[_random.nextInt(19)],
                        pK: colors[_random.nextInt(19)],
                        pL: colors[_random.nextInt(19)],
                        pM: colors[_random.nextInt(19)],
                        pN: colors[_random.nextInt(19)],
                        pR: colors[_random.nextInt(19)],
                        pS: colors[_random.nextInt(19)],
                        pT: colors[_random.nextInt(19)],
                        pW: colors[_random.nextInt(19)],
                        pY: colors[_random.nextInt(19)],
                        qA: colors[_random.nextInt(19)],
                        rE: colors[_random.nextInt(19)],
                        rO: colors[_random.nextInt(19)],
                        rS: colors[_random.nextInt(19)],
                        rU: colors[_random.nextInt(19)],
                        rW: colors[_random.nextInt(19)],
                        sA: colors[_random.nextInt(19)],
                        sB: colors[_random.nextInt(19)],
                        sC: colors[_random.nextInt(19)],
                        sD: colors[_random.nextInt(19)],
                        sE: colors[_random.nextInt(19)],
                        sG: colors[_random.nextInt(19)],
                        sH: colors[_random.nextInt(19)],
                        sI: colors[_random.nextInt(19)],
                        sJ: colors[_random.nextInt(19)],
                        sK: colors[_random.nextInt(19)],
                        sL: colors[_random.nextInt(19)],
                        sM: colors[_random.nextInt(19)],
                        sN: colors[_random.nextInt(19)],
                        sO: colors[_random.nextInt(19)],
                        sR: colors[_random.nextInt(19)],
                        sS: colors[_random.nextInt(19)],
                        sT: colors[_random.nextInt(19)],
                        sV: colors[_random.nextInt(19)],
                        sX: colors[_random.nextInt(19)],
                        sY: colors[_random.nextInt(19)],
                        sZ: colors[_random.nextInt(19)],
                        tC: colors[_random.nextInt(19)],
                        tD: colors[_random.nextInt(19)],
                        tF: colors[_random.nextInt(19)],
                        tG: colors[_random.nextInt(19)],
                        tH: colors[_random.nextInt(19)],
                        tJ: colors[_random.nextInt(19)],
                        tK: colors[_random.nextInt(19)],
                        tL: colors[_random.nextInt(19)],
                        tM: colors[_random.nextInt(19)],
                        tN: colors[_random.nextInt(19)],
                        tO: colors[_random.nextInt(19)],
                        tR: colors[_random.nextInt(19)],
                        tT: colors[_random.nextInt(19)],
                        tV: colors[_random.nextInt(19)],
                        tW: colors[_random.nextInt(19)],
                        tZ: colors[_random.nextInt(19)],
                        uA: colors[_random.nextInt(19)],
                        uG: colors[_random.nextInt(19)],
                        uM: colors[_random.nextInt(19)],
                        uS: colors[_random.nextInt(19)],
                        uY: colors[_random.nextInt(19)],
                        uZ: colors[_random.nextInt(19)],
                        vA: colors[_random.nextInt(19)],
                        vC: colors[_random.nextInt(19)],
                        vE: colors[_random.nextInt(19)],
                        vG: colors[_random.nextInt(19)],
                        vI: colors[_random.nextInt(19)],
                        vN: colors[_random.nextInt(19)],
                        vU: colors[_random.nextInt(19)],
                        wF: colors[_random.nextInt(19)],
                        wS: colors[_random.nextInt(19)],
                        xK: colors[_random.nextInt(19)],
                        yE: colors[_random.nextInt(19)],
                        yT: colors[_random.nextInt(19)],
                        zA: colors[_random.nextInt(19)],
                        zM: colors[_random.nextInt(19)],
                        zW: colors[_random.nextInt(19)],
                      ).toMap(),
                    ),
                  ),
                  // Creates 8% from right side so the map looks more centered.
                  Container(width: MediaQuery.of(context).size.width * 0.08),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}